name: Build & Push add‑on image          # ← shows in the Actions tab

on:                                      # ← WHEN to run
  push:
    branches: [main]                     # run on every commit to main
    # tags: ['v*']                       # uncomment to run on version tags too

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write                    # needed if you ever fall back to GITHUB_TOKEN

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Log in to GHCR with PAT
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}   # ← add this repo secret

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build & push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        provenance: false                   # temp workaround
        tags: |
          ghcr.io/${{ github.repository_owner }}/woolworths_loyalty_points:latest
          ghcr.io/${{ github.repository_owner }}/woolworths_loyalty_points:${{ github.sha }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}

